export const DUMMY_CARD_LIST = [
  {
    name: "박규성",
    email: "email@gmail.com",
    phoneNumber: "01012345678",
    position: "FRONT_END" as const,
    organization: "소속",
    annual: 4,
    profileImageUrl: "이미지 URL",
    introduce: "간단한 자기소개",
    githubUrl: "https://github.com/jacobhboy",
    linkedInUrl: "https://linkedIn.com/asdf",
    instagramUrl: "https://instagram.com/asdf",
  },
  {
    name: "박규성",
    email: "email@gmail.com",
    phoneNumber: "01012345678",
    position: "FRONT_END" as const,
    organization: "소속",
    annual: 4,
    profileImageUrl: "이미지 URL",
    introduce: "간단한 자기소개",
    githubUrl: "https://github.com/jacobhboy",
    linkedInUrl: "https://linkedIn.com/asdf",
    instagramUrl: "https://instagram.com/asdf",
  },
  {
    name: "박규성",
    email: "email@gmail.com",
    phoneNumber: "01012345678",
    position: "FRONT_END" as const,
    organization: "소속",
    annual: 4,
    profileImageUrl: "이미지 URL",
    introduce: "간단한 자기소개",
    githubUrl: "https://github.com/jacobhboy",
    linkedInUrl: "https://linkedIn.com/asdf",
    instagramUrl: "https://instagram.com/asdf",
  },
];
