import Card from "@/components/Card";
import Head from "next/head";

const DUMMY_CARD_DATA = {
  name: "name",
  email: "email@gmail.com",
  phoneNumber: "01012345678",
  position: "FRONT_END" as const,
  organization: "소속",
  annual: 4,
  profileImageUrl: "이미지 URL",
  introduce: "간단한 자기소개",
  githubUrl: "https://github.com/jacobhboy",
  linkedInUrl: "https://linkedIn.com/asdf",
  instagramUrl: "https://instagram.com/asdf",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Card cardData={DUMMY_CARD_DATA} />
      </Head>
    </>
  );
}
